language: ruby
rvm:
  - 2.2
bundler_args: --without production
bundler_args: --binstubs

services:
  - postgresql

before_script:
  - psql -c 'create database livreiro_test;' -U postgres

addons:
  code_climate:
    repo_token: 60f6cd076600fad7cf226d02433f169a55bee9d306717397db531883380f59e0
