version: '2'
services:
  nginx:
    build: ./nginx/prod
    restart: always
    ports:
      - 80:80
    volumes_from:
      - web
    depends_on:
      - web
  db:
    image: postgres
    env_file: .env.production
  web:
    image: webgoal/livreiro
    command: bundle exec unicorn_rails -c config/unicorn.rb
    env_file: .env.production
    volumes:
      - /opt/livreiro/public/assets
    volumes_from:
      - assets
    depends_on:
      - db
