development: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  database: <%= ENV['POSTGRES_DB'] %>
  username: <%= ENV['POSTGRES_USER'] %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>
  host: db

test:
  <<: *default
  database: livreiro_test
